sudo: required
language: node_js
node_js:
- node
install:
- npm install
addons:
  sonarcloud:
    organization: carlsonorozco-github
    token:
      secure: kAIYJPa0lEvF+KhwsYHvwxEmvEySlshmJP8QxeI8IzzW5ndULWG1sB2B81E/UZ8pgGyM1BlW3N2VV0A+F8QZmbRqiN3jQAz3DsWQHJTEEGxl0sjJeKJ3Vw1mtGqdkJ7tziHVsP4QO5zvLxrb0ul1xJ0QwxoaMbGp6ErY1dIJYttF01y4RtsyNAaQz3VHr3oyMT03oJTZNt9Pq8mTpo+60Kj+ydogtlfVZ/IeG5hKJ2hH0YNw3zxZ6mB5EXo45PAw5tf5d6YjWVyxHX71yuZ/H+6G9I77JEnMf0iN/c3zo+gxUL54SagmAaowoHK8NfwSKT/1JW9Akw+vUqcQs9TMWn+ZqjQ8RPPSHFkaPVxHPACJvVnh35E12VXqPXFYTombQRxKB0xHRpX2fOdUXvRl6C84s5u4YTWX7Mf8q6evEUevSUnlMnEyLdfMBjom3Q3zKZ1/ddg26CGORhEGTiNs/QLMXhb/65L0HULgCYYh4vcUC/G68yKs5blzi81yxntiHuAAKn8Hn5MFJqeHoTnzQvjnRdwQh+3WaSbxzuIhlKyJTqsp2KtV3c4jC8iSZ1axq4gPlVYSKAqjn4KGjAi2z7Jbb3W0h/op2QpYpFunGalGZFdI0NWlktBGvBAM7CopBYrbl/dCI9VRoXGyoj11cw/DlHPJM0JfdiMO5bOvfAw=
script:
- sonar-scanner
cache:
  directories:
  - $HOME/.sonar/cache
